Proyecto_PGPI/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from Tienda import views
from Tienda.Factura import views as viewsFactura
from Tienda.Producto import views as producto_views
from django.contrib.auth.views import LogoutView
from Tienda.Usuario import views as usuario_views

urlpatterns = [
    path('', views.pagina_principal, name='pagina_principal'),
    path('admin/', admin.site.urls),

    path('cart/', include('cart.urls', namespace='cart')),
    path('cart-count/', views.cart_count_view),
 
    path('usuarios/', views.lista_usuarios, name='lista_usuarios'),
    path('login/', views.login_view, name='login'),
    path('logout/', LogoutView.as_view(next_page='/'), name='logout'),
    path('register/', views.register_view, name='register'),
    path('editar-perfil/', usuario_views.edit_profile, name='edit_profile'),
    path('lista-usuarios/', usuario_views.user_list, name='user_list'),
    path('editar-usuario/<int:user_id>/', usuario_views.edit_user, name='edit_user'),
    path('crear-usuario/', usuario_views.create_new_user, name='crear_usuario'),
    path('eliminar_usuario/<int:user_id>/', usuario_views.delete_user, name='delete_user'),

    path('facturas/', views.lista_facturas, name='lista_facturas'),
    path('factura/<int:factura_id>/', viewsFactura.modificar_factura, name="factura_admin"),
    path('factura/confirmar', viewsFactura.confirmar_factura, name='crear_pedido'),
    path('factura/numero_factura/<str:numero_factura>', viewsFactura.obtener_factura_por_numero_factura, name='buscar_factura_por_numero'),
    
    # path('crear-sesion-pago/', viewsFactura.crear_sesion_pago, name='crear_sesion_pago'),
    path('cancelar_factura', viewsFactura.cancelar_factura, name='cancelar_factura'),
    path('procesar_pago/<str:numero_factura>', viewsFactura.procesar_pago, name="procesar_pago"),
    
    path('productos/', views.lista_productos, name='lista_productos'),
    path('productos/<int:producto_id>/', producto_views.detalle_producto, name='detalle_producto'),
    path('productos/crear/', producto_views.crear_producto, name='crear_producto'),
    path('producto/<int:producto_id>/editar/', producto_views.actualizar_producto, name='actualizar_producto'),
    path('productos/<int:producto_id>/eliminar/', producto_views.eliminar_producto, name='eliminar_producto'),

    path('categorias/', views.lista_categorias, name='lista_categorias'),
    path('categorias/<int:categoria_id>/', producto_views.lista_productos_de_categoria, name='lista_productos_categoria'),
    path('categorias/crear/', producto_views.crear_categoria_de_producto, name='crear_categoria'),
    path('categorias/<int:categoria_de_producto_id>/editar/', producto_views.ver_actualizar_categoria_de_producto, name='ver_actualizar_categoria'),
    path('categorias/<int:categoria_de_producto_id>/editado/', producto_views.actualizar_categoria_de_producto, name='actualizar_categoria'),
    path('categorias/<int:categoria_de_producto_id>/eliminar/', producto_views.eliminar_categoria_de_producto, name='eliminar_categoria'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path

from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/<int:llevar_a_carrito>', views.cart_add, name='cart_add'),
    path(
        'remove/<int:product_id>/',
        views.cart_remove,
        name='cart_remove',
    ),
]

cart/forms.py
from django import forms


class CartAddProductForm(forms.Form):
    cantidad = forms.IntegerField(
        required=False,
        initial=1,
        min_value=1
    )
    sobreescribir = forms.BooleanField(
        required=False,
        initial=False,
        widget=forms.HiddenInput
    )

    def __init__(self, *args, **kwargs):
        stock = kwargs.pop('stock', None)
        super().__init__(*args, **kwargs)
        if stock is not None:
            self.fields['cantidad'].widget.attrs['max'] = stock

cart/views.py
from django.shortcuts import get_object_or_404, redirect, render
from django.views.decorators.http import require_POST
from django.contrib import messages
from Tienda.models import Producto

from .cart import Cart
from .forms import CartAddProductForm


@require_POST
def cart_add(request, product_id, llevar_a_carrito):
    cart = Cart(request)
    product = get_object_or_404(Producto, id=product_id)
    form = CartAddProductForm(request.POST)

    cantidad_actual = cart.cart.get(str(product_id))
    if cantidad_actual is None:
        cantidad_actual = 0
    else:
        cantidad_actual = cantidad_actual["cantidad"]

    if form.is_valid():
        cd = form.cleaned_data  
        cantidad = int(request.POST.get("cantidad")) if request.POST.get("cantidad") is not None else 0
        if cantidad == None:
            cantidad = 1
        if cantidad + cantidad_actual <= product.stock:
            cart.add(
                producto=product,
                cantidad=cantidad,
                sobreescribir_cantidad=cd["sobreescribir"],
            )
        else:
            messages.error(request, f"El limite de cantidad del producto {product.nombre} es {product.stock}")
    if llevar_a_carrito == 0:
        referer_url = request.META.get('HTTP_REFERER', '')
        return redirect(referer_url)
    else:
        return redirect('cart:cart_detail')


@require_POST
def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Producto, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(
            initial={'cantidad': item['cantidad'], 'sobreescribir': True}, stock = item["producto"].stock
        )
        
    return render(
        request,
        'cart/detail.html',
        {
            'cart': cart,
        },
    )

cart/templates/cart/detail.html
{% extends 'base.html' %}

{% block title %}Aura Arcana{% endblock %}

{% block content %}
<section class="main-content1">
  <div class="title-container" style="margin-top: 210px;"><h2>Crear pedido</h2>
    <div>
      <table class="cart">
        <thead>
          <tr>
            <th>Imagen</th>
            <th>Producto</th>
            <th>Cantidad</th>
            <th>Editar</th>
            <th>Eliminar</th>
            <th>Precio Unitario</th>
            <th>Precio total</th>
          </tr>
        </thead>
        <tbody>
          {% for item in cart %}
          {% with producto=item.producto %}
          <tr>
            <td><img src="{{ producto.fotografia.url }}"></td>
            <td>{{ producto.nombre }}</td>
            <td>
              <form action="{% url 'cart:cart_add' producto.id 0 %}" method="post">
                {{ item.update_quantity_form.cantidad }}
                {{ item.update_quantity_form.sobreescribir }}
                <td><input type="submit" value="✅"></td>
                {% csrf_token %}
              </form>
            </td>
            <td>
              <form action="{% url 'cart:cart_remove' producto.id %}"  method="post">
                <input type="submit" value="🗑️">
                {% csrf_token %}
              </form>
            </td>
            <td class="num">{{ item.precio }}€</td>
            <td class="num">{{ item.total_precio }}€</td>
          </tr>
          {% endwith %}
          {% endfor %}
          
          <tr class="total">
            <td>Total</td>
            <td colspan="4"></td>
            <td class="num">
              {{ cart.get_total_precio|floatformat:2 }}€
            </td>
          </tr>
        </tbody>
      </table>
      <tr>
        <td colspan="7" style="text-align: center;">
          <div style="display: flex; justify-content: center; gap: 20px; margin-top: 20px;">
          {% if cart and cart|length > 0 %}
          <button id="confirmar" onclick="window.location.href = '/factura/confirmar'" style="background-color: #4caf50;">Confirmar</button>
          {% endif %}
          <button id="volver" onclick="window.history.back()">Volver</button>
          </div>
        </td>
      </tr>
    </div>
      
  </div>
  <style>
      .mensaje-error {
          color: white;
          background-color: red;
          padding: 10px 20px;
          border-radius: 5px;
          font-size: 16px;
          font-weight: bold;
          text-align: center;
          margin: 10px 0;
      }

      .main-content1 {
        display: flex;
        flex-direction: column;
        height: auto;
        min-height: 90vh;
      }

      /* Tabla */
      table.cart {
          width: 80%;
          margin-right: 10%;
          margin-left: 10%;
          border-collapse: collapse;
          overflow: hidden;
          border-radius: 8px;
          background-color: #ffffff;
          box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
      }

      thead {
          background-color: #006e6f;
          color: #ffffff;
      }

      thead th {
          padding: 15px;
          font-weight: bold;
          font-size: 1em;
      }

      tbody tr {
          transition: background-color 0.3s;
      }

      tbody tr:hover {
          background-color: #f1f5f9;
      }

      /* Celdas */
      td {
          padding: 15px;
          text-align: center;
          font-size: 0.9em;
          color: #333;
      }

      td img {
          max-width: 60px;
          max-height: 60px;
          border-radius: 5px;
          box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
      }

      /* Botón de remover */
      td button {
          width: 40px;
          padding: 10px 15px;
          background-color: #ff4c4c;
          color: #fff;
          border: none;
          border-radius: 4px;
          cursor: pointer;
          transition: background-color 0.3s ease;
          box-shadow: 0 2px 5px rgba(0, 0, 0, 0.15);
      }


      td button:hover {
          background-color: #e62e2e;
      }

      /* Precio */
      td:last-child,
      td:nth-last-child(2) {
          font-weight: bold;
          color: #555;
      }
      button:hover {
          background-color:#006e6f;
      }

      
      .icon {
          color: #006e6f;
      }

      .icon:hover {
          color:#006e6f;
      }

      input[type="number"] {
          font-size: 18px;
          padding: 12px;
          width: 100px;
          border: 2px solid #ddd;
          border-radius: 8px;
          outline: none;
          background-color: #fafafa;
          transition: border-color 0.3s, box-shadow 0.3s;
      }

      input[type="number"]:focus {
          border-color: #4caf50;
          box-shadow: 0 0 10px rgba(76, 175, 80, 0.2);
      }

      input[type="number"]:hover {
          border-color: #888;
      }

      /* Ocultar las flechitas en los campos de tipo number */
      input[type="number"]::-webkit-outer-spin-button,
      input[type="number"]::-webkit-inner-spin-button {
          -webkit-appearance: none;
          margin: 0;
      }

      /* Estilo de la tabla en dispositivos móviles */
      @media (max-width: 768px) {
          .formulario input {
              width: 80%;
          }

          table,
          thead tr,
          tbody tr {
              display: block;
              width: 100%;
          }

          thead {
              display: none;
          }
      }
  </style>

  
</section>

{% endblock %}